nodes:
  - id: 1
    address: "127.0.0.1"
    port: 5001
  - id: 2
    address: "127.0.0.1"
    port: 5002
  - id: 3
    address: "127.0.0.1"
    port: 5003
  - id: 4
    address: "127.0.0.1"
    port: 5004
  - id: 5
    address: "127.0.0.1"
    port: 5005
election_timeout: 500
heartbeat_timeout: 100