### PUT key-value pair (only works on leader node)
POST http://localhost:7001/put
Content-Type: application/json

{
  "key": "foo",
  "value": "bar"
}

### GET value by key
GET http://localhost:7003/get/foo

### Test redirection behavior (if this node is not the leader)
POST http://localhost:18080/put
Content-Type: application/json

{
  "key": "another",
  "value": "test"
}
